apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: portfolio-image
  namespace: portfolio-project
spec:
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: ghcr.io/sysopsxpert/portfolio-website:latest
    referencePolicy:
      type: Source
    importPolicy:
      scheduled: false # Set to false to disable automatic registry polling
